### PR TITLE
Bump MySQL version

### PR DESCRIPTION
**Pull request by Kampfkarren**

### CODE REVIEW

**Comment by zimond** [comment]
Ping @outersky

**Comment by Kampfkarren** [comment]
If you need this now, you can use `{ git = "https://github.com/Kampfkarren/r2d2-mysql" }` in your Cargo.toml, or something like that.

**Comment by zimond** [comment]
> If you need this now, you can use `{ git = "https://github.com/Kampfkarren/r2d2-mysql" }` in your Cargo.toml, or something like that.

I know, just want this to be landed

**Comment by omikuji** [comment]
Currentry, with reference to README.md, I can not build it even if i write `r2d2_mysql = "*"`. but write `{ git = "https://github.com/Kampfkarren/r2d2-mysql" }`, i can build.

I hope this pull request will come soon!

**Comment by zimond** [comment]
@outersky please release a new version

**Comment by outersky** [comment]
@zimond done

**Pull request merged**
