### PR TITLE
Update mysql to 19

### PR DESCRIPTION
**Pull request by SergioBenitez**
As in the title.

P.S: Rust libraries should not have a `Cargo.lock` file. Is there a reason this crate has one?

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Ping! Is this crate being maintained?

**Comment by sinshutu** [comment]
Dependency seems to have been updated to mysql-20 in # 26

But not released

See https://github.com/rust-lang/crates.io-index/blob/74f9b73639a45fc0c0f5fe1df1465ae50096a099/r2/d2/r2d2_mysql

**Comment by SergioBenitez** [comment]
In any case, I think the lack of activity answers my previous question.

**Comment by outersky** [comment]
sorry , just published v20.0.0

**Pull request closed without merging**
