### PR TITLE
override default healthcheck support

### PR DESCRIPTION
**Pull request by momo-p**
I'm currently using this crate to communicate with my manticore server, even though it's compatible wit MySQL but for some reason it's not support `SELECT version()` which make the default healthcheck always throw error.

So I'm adding a feature to override the default healthcheck function.

### CODE REVIEW

**Comment by robjtede** [comment]
Is there any reason not to just change the current health check query to `SELECT 1`?

**Comment by momo-p** [comment]
> Is there any reason not to just change the current health check query to `SELECT 1`?

Maybe I over-engineered it a little bit, but I think it could be for future-proofing.

Like in case query log enabled for debugging and you don't want it full of `SELECT 1` in the logs and your database support it you could swap it with the `.ping()` call

**Comment by robjtede** [comment]
Even better, would be nice if `ping` returned `Result<(), Error>` then it would be a no-brainer to switch to.

For now I'm tempted to change it to `SELECT 1`.

**Comment by momo-p** [comment]
the current [`ping()` method](https://docs.rs/mysql/latest/mysql/struct.Conn.html#method.ping) in the mysql crate return `bool` so I believe it would took a few more step.

what I really concern at that time (sorry I wrote those at 3AM :D) is that give it a little more flexibility, who knows if some future sql-like database in the future support `COM_PING` or their parser accept `SELECT 1;`, so I add it just-in-case needed

**Comment by robjtede** [comment]
Pushed a change that:
- uses more standard type naming
- changes the signature of `HealthCheckFn` to a function pointer
  - this is equivalent in the fns it accepts to what you'd written before with the &'static bound on `health_check_fn`s param to `with_custom_health_check` but avoids the Arc overhead

**Comment by robjtede** [comment]
@outersky curious what you think. I'm hesitant but seems that my PR https://github.com/blackbeam/rust-mysql-simple/pull/355 to change the `.ping()` signature is slow going so might be a nice QoL change, for now at least. (My feeling is that we necessarily push enough major versions that it could be removed without to much hassle in the future.)

**Comment by robjtede** [comment]
Also for the CI fail: We'll rebase this after #37 is merged.

**Comment by robjtede** [comment]
superseded by #38

**Pull request closed without merging**
